services:
  amo-ui:
    build: .
    container_name: amo-ui
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
    restart: unless-stopped
    networks:
      - amo-net

networks:
  amo-net:
    external: true
    name: amo_default
